site_name: "macos-cfg-docs"
docs_dir: "./macos-cfg-docs/"

theme:
  name: "material"
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "deep purple"
      accent: "deep purple"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "deep purple"
      accent: "deep purple"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - def_list
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

plugins:
  - search
  - offline
  - roamlinks

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

nav:
  - Overview: index.md
  - System Settings: macos_settings.md
  - Essential Tools: essential_tools.md
  - Potentially Nice: potentially_nice.md
